version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    depends_on:
      - backend
    networks:
      - hogarzen-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ../backend/.env.local
    networks:
      - hogarzen-network

networks:
  hogarzen-network:
    driver: bridge 